[package]
name = "codeforces-extractor"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
chromiumoxide = "0.8.0"
tl = "0.7.8"
tokio = { version = "1.42.0", features = ["full"] }
futures = "0.3.31"
